---
- src: https://github.com/racciari/ansible-role-repo-openio-sds
  version: master
  name: repository

- src: https://github.com/open-io/ansible-role-openio-gridinit.git
  version: master
  name: gridinit
...
