# roles/ansible-role-memcached/tasks/main.yml
---
- name: "Include {{ ansible_distribution }} variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: install

- name: "Include {{ ansible_distribution }} tasks"
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: install
  register: _memcached_pkg

- name: restart memcached
  command: >-
    "gridinit_cmd restart 
    {{openio_memcached_namespace}}-memcached-{{openio_memcached_serviceid}}"
  when: _memcached_pkg.changed
