# roles/memcached/tasks/main.yml
---

- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: memcached

- name: Install packages
  package:
    name: "{{ item }}"
    state: installed
  with_items: "{{ memcached_packages }}"
  tags: memcached

- name: Ensure service is started
  service:
    name: "{{ memcached_service }}"
    state: started
    enabled: true
  tags: memcached
